-- NPC 상점 GUI에서 수집한 일별 판매가 샘플
create table if not exists public.npc_market_price_samples (
  id bigint generated by default as identity primary key,
  item_name text not null,
  price integer not null check (price > 0),
  price_date date not null default (timezone('utc', now()))::date,
  server text not null default 'ddingtycoon',
  submitted_at timestamptz not null default now()
);

create index if not exists npc_market_price_samples_lookup_idx
  on public.npc_market_price_samples (server, price_date, item_name);
