/* Auto-generated by npm run build from SUPABASE_URL / SUPABASE_ANON_KEY */
window.__SUPABASE_CONFIG__ = {"url":"https://noavfecpraqoitsyzonr.supabase.co","anonKey":"sb_publishable_G4hh4mTl27AsyZuTrDtH_A_wMQ0yPMM"};
