/**
 * Auto-generated by npm run build — Discord 포털용 주소는 discordOAuthRedirectUri 참고
 */
window.SUPABASE_CONFIG = {"url":"https://noavfecpraqoitsyzonr.supabase.co","anonKey":"sb_publishable_G4hh4mTl27AsyZuTrDtH_A_wMQ0yPMM","oauthRedirectUrl":"https://ddingtycoon-01.vercel.app/auth/callback","discordOAuthRedirectUri":"https://noavfecpraqoitsyzonr.supabase.co/auth/v1/callback"};
