/**
 * Reads SUPABASE_URL and SUPABASE_ANON_KEY from the environment
 * and writes supabase-config.js for static hosting (local / Vercel).
 */
const fs = require('fs');
const path = require('path');

const url = process.env.SUPABASE_URL || '';
const anonKey = process.env.SUPABASE_ANON_KEY || '';

const content = `/* Auto-generated by npm run build. Set SUPABASE_URL and SUPABASE_ANON_KEY in the environment. */
window.__SUPABASE_CONFIG__ = ${JSON.stringify({ url, anonKey })};
`;

const outPath = path.join(__dirname, '..', 'supabase-config.js');
fs.writeFileSync(outPath, content, 'utf8');
process.stdout.write(
  `[generate-env] ${path.basename(outPath)} → url: ${url ? 'yes' : 'empty'}, anonKey: ${anonKey ? 'yes' : 'empty'}\n`
);
