/**
 * Reads SUPABASE_URL and SUPABASE_ANON_KEY from .env (local) or process.env (Vercel CI),
 * writes supabase-config.js for static hosting.
 */
const fs = require('fs');
const path = require('path');

try {
  require('dotenv').config({ path: path.join(__dirname, '..', '.env') });
} catch (e) {
  console.warn('[generate-env] dotenv optional load skipped:', e && e.message);
}

const url = process.env.SUPABASE_URL || '';
const anonKey = process.env.SUPABASE_ANON_KEY || '';

const content = `/* Auto-generated by npm run build from SUPABASE_URL / SUPABASE_ANON_KEY */
window.__SUPABASE_CONFIG__ = ${JSON.stringify({ url, anonKey })};
`;

const outPath = path.join(__dirname, '..', 'supabase-config.js');
fs.writeFileSync(outPath, content, 'utf8');
process.stdout.write(
  `[generate-env] ${path.basename(outPath)} url:${url ? 'yes' : 'empty'} anonKey:${anonKey ? 'yes' : 'empty'}\n`
);
