/**
 * Node.js 빌드 전용 — 브라우저에서는 실행되지 않습니다.
 * 프로젝트 루트의 .env 파일을 읽거나, CI에서 설정된 환경값으로 supabase-config.js를 생성합니다.
 */
const fs = require('fs');
const path = require('path');

function parseEnvFile(filePath) {
  const out = {};
  try {
    const raw = fs.readFileSync(filePath, 'utf8');
    for (const line of raw.split(/\r?\n/)) {
      const t = line.trim();
      if (!t || t.startsWith('#')) continue;
      const eq = t.indexOf('=');
      if (eq <= 0) continue;
      const key = t.slice(0, eq).trim();
      let val = t.slice(eq + 1).trim();
      if (
        (val.startsWith('"') && val.endsWith('"')) ||
        (val.startsWith("'") && val.endsWith("'"))
      ) {
        val = val.slice(1, -1);
      }
      out[key] = val;
    }
  } catch (_) {
    /* no .env file */
  }
  return out;
}

const root = path.join(__dirname, '..');
const fileEnv = parseEnvFile(path.join(root, '.env'));
const url =
  fileEnv.SUPABASE_URL ||
  (typeof process !== 'undefined' && process.env && process.env.SUPABASE_URL) ||
  '';
const anonKey =
  fileEnv.SUPABASE_ANON_KEY ||
  (typeof process !== 'undefined' && process.env && process.env.SUPABASE_ANON_KEY) ||
  '';

const content = `/* Auto-generated by npm run build — do not edit */
window.SUPABASE_CONFIG = ${JSON.stringify({ url, anonKey })};
`;

const outPath = path.join(root, 'supabase-config.js');
fs.writeFileSync(outPath, content, 'utf8');
process.stdout.write(
  `[generate-env] ${path.basename(outPath)} url:${url ? 'yes' : 'empty'} anonKey:${anonKey ? 'yes' : 'empty'}\n`
);
